- fix backward navigation on ctrl+f search bar
With scoped enums in Qt6 a click on the "up" button, i.e. search
backwards causes pykib to crash with an error

    AttributeError: type object 'OWebEnginePage' has no attribute
    'FindBackward'

Passing the qualified enum value QWebEnginePage.FindFlag.FindBackward
resolves this issue.